package com.wyu.seckill.entity;

import java.util.Date;

public class User11 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.openid
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.nick_name
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.phone
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.name
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.certificates_type
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    private String certificatesType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.certificates_no
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    private String certificatesNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.certificates_url
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    private String certificatesUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.auth_status
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    private Byte authStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.status
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_time
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.update_time
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.is_deleted
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    private Byte isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.openid
     *
     * @return the value of user_info.openid
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.openid
     *
     * @param openid the value for user_info.openid
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.nick_name
     *
     * @return the value of user_info.nick_name
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.nick_name
     *
     * @param nickName the value for user_info.nick_name
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.phone
     *
     * @return the value of user_info.phone
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.phone
     *
     * @param phone the value for user_info.phone
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.name
     *
     * @return the value of user_info.name
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.name
     *
     * @param name the value for user_info.name
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.certificates_type
     *
     * @return the value of user_info.certificates_type
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    public String getCertificatesType() {
        return certificatesType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.certificates_type
     *
     * @param certificatesType the value for user_info.certificates_type
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    public void setCertificatesType(String certificatesType) {
        this.certificatesType = certificatesType == null ? null : certificatesType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.certificates_no
     *
     * @return the value of user_info.certificates_no
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    public String getCertificatesNo() {
        return certificatesNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.certificates_no
     *
     * @param certificatesNo the value for user_info.certificates_no
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    public void setCertificatesNo(String certificatesNo) {
        this.certificatesNo = certificatesNo == null ? null : certificatesNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.certificates_url
     *
     * @return the value of user_info.certificates_url
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    public String getCertificatesUrl() {
        return certificatesUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.certificates_url
     *
     * @param certificatesUrl the value for user_info.certificates_url
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    public void setCertificatesUrl(String certificatesUrl) {
        this.certificatesUrl = certificatesUrl == null ? null : certificatesUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.auth_status
     *
     * @return the value of user_info.auth_status
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    public Byte getAuthStatus() {
        return authStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.auth_status
     *
     * @param authStatus the value for user_info.auth_status
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    public void setAuthStatus(Byte authStatus) {
        this.authStatus = authStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.status
     *
     * @return the value of user_info.status
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.status
     *
     * @param status the value for user_info.status
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.create_time
     *
     * @return the value of user_info.create_time
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.create_time
     *
     * @param createTime the value for user_info.create_time
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.update_time
     *
     * @return the value of user_info.update_time
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.update_time
     *
     * @param updateTime the value for user_info.update_time
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.is_deleted
     *
     * @return the value of user_info.is_deleted
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.is_deleted
     *
     * @param isDeleted the value for user_info.is_deleted
     *
     * @mbg.generated Thu Nov 25 16:44:20 CST 2021
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
}